ruby:
  config_file: https://raw.githubusercontent.com/bukowskis/style-guide/master/rubocop.yml
scss:
  config_file: https://raw.githubusercontent.com/bukowskis/style-guide/master/scss-lint.yml
eslint:
  enabled: true
  config_file: https://raw.githubusercontent.com/bukowskis/style-guide/master/.eslintrc
coffeescript:
  config_file: https://raw.githubusercontent.com/bukowskis/style-guide/master/coffeelint.json

fail_on_violations: true
