version: '3.4'

x-shared: &shared
    build:
      context: .
      dockerfile: ./Dockerfile
    tmpfs:
      - /tmp
    volumes:
      - ~/Projects:/Projects:cached

services:
  runner:
    <<: *shared
    stdin_open: true
    tty: true
    command: /bin/bash
