version: '3.4'

x-shared: &shared
    build:
      context: .
      dockerfile: ./Dockerfile
    tmpfs:
      - /tmp

services:
  pronto:
    <<: *shared
    stdin_open: true
    tty: true
    command: /bin/bash -c 'pronto run -f json 2> /dev/null'
